### ISSUE TITLE
[Error] NetworkManager 

### ISSUE THREAD

**Issue by roniprog** [FizzCube/SteamNetNetworkTransport#1]
Hello! Thanks for great peer to peer transport! I have 2 questions.
What is the best way for the client to check if the host left the game?
I'm using LobbyDataUpdate_t but i'm not pretty sure that's is the good solution for many of players.
`if (Convert.ToBoolean(pCallback.m_bSuccess) && pCallback.m_ulSteamIDLobby == steamLobbyId.m_SteamID){
            int numMembers = SteamMatchmaking.GetNumLobbyMembers(steamLobbyId);
            bool ownerLeft = true;
            for (int i = 0; i < numMembers; i++)
            {
                var member = SteamMatchmaking.GetLobbyMemberByIndex(steamLobbyId, i);
                if (member.m_SteamID == steamRemoteId.m_SteamID)
                {
                    ownerLeft = false;
                    break;
                }
            }
            if (ownerLeft)
            {
                    LeaveLobby();
            }
        }`

And secondly.. when the host leaves the game and re-creates the server, and the client joins the host...the client and the host get errors. What's wrong with my code?
`public void StopSteam()
    {
        SteamMatchmaking.LeaveLobby(sID);
        ResetSID(sID);
        if (NetworkServer.active)
        {
            StopServer();
        }
        else
        {
            m_steamLobbyDataUpdate.Dispose();
            m_steamLobbyDataUpdate = null;

            if (client != null)
            {
                StopClient();
            }
        }
    }`

**Comment by TimPickup** [comment]
Hi,
Thanks for your report @roniprog. Sorry I missed it until now.

I'm aware now there is an issue with the disconnect code and I'm going to take a look at that now.

Regarding knowing the host has left - Mirrors disconnect functionality _Should_ work - although there could be more of a delay to realise than a TCP connection but we can work to realise that asap - so something like NetworkManagers OnServerDisconnect.

I will update you when the disconnect code is fixed

**Comment by TimPickup** [comment]
Hi @roniprog, I believe I have fixed the issues with disconnecting.

Please update (and update to latest Mirror version) and let me know if its resolved for you

**Comment by roniprog** [comment]
Hi, thanks for responding!
Ok so.. when host leave the lobby and create new one that's works good. But when the other client joins to the lobby and host leave the game then create new lobby client firstly has a message 'A connection has already been set as ready! There can only be one. Host has the message 'Received NetworkTransform data for GameObject that doesn't exist NullReferenceException'

**Comment by TimPickup** [comment]
@roniprog I have done some updates and believe this is all fixed.. There are also 2 pll requests to Mirror which will fix related disconnect/reconnect issues, so when they are merged I think it should be solid, so please re test then. they are
https://github.com/vis2k/Mirror/pull/129
and
https://github.com/vis2k/Mirror/pull/130
Thanks for testing. Feel free to join us in Discord. We have a channel specifically for Steam https://discord.gg/AWJMT5Q
